package Example;


/**
* Example/Echo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../echo.idl
* Dienstag, 13. Januar 2015 13:37 Uhr MEZ
*/

public interface Echo extends EchoOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Echo
