package Example;

/**
* Example/EchoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../echo.idl
* Dienstag, 13. Januar 2015 13:37 Uhr MEZ
*/

public final class EchoHolder implements org.omg.CORBA.portable.Streamable
{
  public Example.Echo value = null;

  public EchoHolder ()
  {
  }

  public EchoHolder (Example.Echo initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Example.EchoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Example.EchoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Example.EchoHelper.type ();
  }

}
