package Example;


/**
* Example/EchoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../echo.idl
* Dienstag, 13. Januar 2015 13:37 Uhr MEZ
*/

public interface EchoOperations 
{
  String echoString (String mesg);
} // interface EchoOperations
